### ISSUE TITLE
How to set up the es-token?

### ISSUE THREAD

**Issue by zhouyisu** [shaoshing/alfred-evernote#3]
Hi, I am bit confused here. After I got the developer token from Evernote, how should I set it in the workflow? Do I just type "es-token" and paste the token right next to it? Should there be a space or something? I simply pressed enter but there is no input window to paste the token. Thanks

**Comment by patricorgi** [comment]
I run into this problem, too. I think the author didn't make this point clear.

**Comment by patricorgi** [comment]
@zhouyisu Do you a China User?

**Comment by zhouyisu** [comment]
@hangyiwu yes I am.

**Comment by patricorgi** [comment]
@zhouyisu 他这个印象笔记的workflow仅支持国际版；我fork了他的这个workflow，改成支持中文版的印象笔记了；你可以到：https://github.com/hangyiwu/alfred-evernote 下载

**Comment by zhouyisu** [comment]
我用的就是国际版……你搞明白了怎么用es-token了？

**Comment by patricorgi** [comment]
@zhouyisu 直接在alfred里执行es-token YOURTOKEN命令就行，如果没有反应，就删掉，然后重新去packal下一次这个workflow

**Comment by zhouyisu** [comment]
@hangyiwu 是在执行完es-token MYTOKEN 之后应该出现什么提示吗？我打进去没反应，然后删了workflow重装，还是没啥反应

**Comment by patricorgi** [comment]
@zhouyisu 
 没错，是有提示成功的，从通知中心。删了重装没用，你要去packal 上重新下载这个workflow。我也不知道什么原理，不过我这样之后就可以使用了。

**Comment by zhouyisu** [comment]
@hangyiwu 问题解决了。我在debug模式下看到作者调用了node.js。所以用户需要安装Npm。

@shaoshing I figure out why I couldn't pass the token verification stage. I didn't have NPM on this new Mac. I install Node then everything works smoothly.
