### ISSUE TITLE
Evernote has suspended DEV tokens creation :(((((

### ISSUE THREAD

**Issue by awinecki** [shaoshing/alfred-evernote#7]
Such a shame, really wanted to use this one.

![developer tokens 2017-10-07 14-51-37](https://user-images.githubusercontent.com/656694/31308006-120d9bb4-ab6f-11e7-8e7d-679d2d6d66f6.png)

FYI: Adding this issue just for others that stumble upon this. So far I see now way of using this workflow because of the above.

**Comment by limacohen** [comment]
2020 Update: Dev token creation seems to be available again, just made mine and it's working fine with the workflow.
